### ISSUE TITLE
各章に振られている章番号がずれている

### ISSUE THREAD

**Issue by nmtake** [y-yu/trpl-2nd-pdf#10]
例えば、原書では第 5 章の構造体についての章が、PDF (おそらく ec673f4 でのビルド）では第 7 章（2 つずれ）になっています。また issue #8 とも関係するのかもしれませんが、原書 14 章の Cargo に関する章は、PDF では 17 章（3 つずれ）になっています。

**Comment by y-yu** [comment]
うーん、最初はMarkdown側の不具合だと思いましたが、ちょっと調査します。

**Comment by scivola** [comment]
原著の第13章までの章番号が，こちらで 2 多い番号にズレている問題は二つ原因があるようです。
一つは，章番号を与えるべきでない [Foreword](https://github.com/rust-lang/book/blob/master/second-edition/src/foreword.md)（邦訳「まえがき」）が一つの章として扱われてしまっていること。
もう一つは，原著で第一章に含まれる「Introduction」と「Getting Started」が二つの章に分かれていることです。

そのあとの章がさらに 1 ずれているのは，ご指摘のとおり #8 のせいです。

付録がおかしいのは *.md ファイルで付録の見出しのマークアップが `#` と `##` で統一されていないせいです。

**Comment by y-yu** [comment]
ひとまず「まえがき」を目次の前に移動させ章番号を取り除きました。これで少しはマシになったと思いますが、残りの問題はMarkdown側を修正するべきと思いますので、いったんこの問題についてはクローズさせていただきます。
