### ISSUE TITLE
一部を除き図表の画像が PDF に埋め込まれていない

### ISSUE THREAD

**Issue by nmtake** [y-yu/trpl-2nd-pdf#11]
原書で使われている画像は「Final Project: Building a Multithreaded
Web Server」（[原書第 20 章](https://doc.rust-lang.org/book/second-edition/ch20-00-final-project-a-web-server.html)）のものを覗いて埋め込まれていないようです。

**Comment by y-yu** [comment]
うーん、ちょっと`setup.sh`で画像を拾ってくるところに問題があったかな……。調査します！
（別のところから流用したスクリプトだとバレてしまう）

**Comment by y-yu** [comment]
@nmtake 

ひとまず #12 で無理やり修正しました。図をもっといい感じにするというIssueは別で作っておいて、ひとまずは解決とさせてください。

**Comment by nmtake** [comment]
修正ありがとうございます！ 図の総数が多くないこともあってひとまずはこれで十分です。  
こちらでも改良できないか PDF をビルドする環境が整ったら調べてみます。
