### ISSUE TITLE
* * による強調はボールドに

### ISSUE THREAD

**Issue by scivola** [y-yu/trpl-2nd-pdf#15]
`* *` で囲んだところですが，欧文はイタリックに，和文は角ゴシックになります。
そうすると，Hello, World の章にある `*AOTコンパイル*` のように，イタリックとゴシックの混じった変な表記になります。

和文がある以上，`* *` による強調はボールド（和文は角ゴシック，欧文はボールドもしくはサンセリフ）にするのがよいと思います。

**Comment by y-yu** [comment]
この問題ですが、現在利用しているIPAフォントにはボールドがたしか無いと記憶しています。（まちがっていたらすいません）
ちょっとそのあたりを調べてみまして、もしIPAフォントにボールドがない場合は源ノ角フォントに変更しようかと思います。
