### ISSUE TITLE
page49 累乗の表記

### ISSUE THREAD

**Issue by tMasaaa** [y-yu/trpl-2nd-pdf#2]
5.2.1.1 第5章>スカラー型>整数型(49ページ目2段落目)に累乗が正しく表記されていない誤りを見つけました。

一行目: 誤: -(2n - 1)から(2n - 1 - 1) → 正: -(2^(n - 1))から(2^(n - 1) - 1)
二行目: 誤: i8型は-(27)から27 - 1まで → 正: i8型は-2^7から2^7 - 1まで
三行目~四行目:
誤: 0から2n - 1まで → 正: 0から2^n - 1まで
誤: 0から28-1までの値 → 0から2^8-1までの値

と思われます。すでに修正済みでしたらすみません。

**Comment by scivola** [comment]
Markdown で `2<sup>7</sup>` のようにマークアップされているところが TeX で上付きになっていないのですね。

調べたところ，`*.md` ファイルで `<sup>` が使われているのはこれらの箇所だけでした。`<sub>` は使われていませんでした。

**Comment by y-yu** [comment]
@tMasaaa @scivola 

なるほど、MarkdownにHTMLを埋め込んであるのですね……。これはpandocfilterで処理しようと思います！
（Markdownはポータビリティが売りのはずなのに、HTMLを詰め込んでしまっていいのか？）
