### ISSUE TITLE
ヘッダーが版面をはみ出している

### ISSUE THREAD

**Issue by scivola** [y-yu/trpl-2nd-pdf#3]
ヘッダー部が版面を右側に大きくはみ出しています。

**Comment by y-yu** [comment]
@scivola 

これはltjsbookの組版の都合なのですが、組版的にあんまりやらないんでしょうか？
（私はLaTeXにはそこそこ詳しいかもしれないんですが、組版の業務経験はないので誰かに力を貸してほしいです……）

**Comment by scivola** [comment]
TeX の知識が 20 年くらい前で止まっていまして（笑），ltjsbook は名前すら今回初めて知ったのですが，デフォルトで版面からはみ出すのですか？　うーん。

もしかすると，本文の版面と傍注エリアを合わせた領域にヘッダーがかかっているのでしょうかね。それならありうるでしょう。その場合，（奇数・偶数でレイアウトを変えないデザインなので）左右のマージンを均等にします。
が，傍注は無いのでしょうから，やはり本文領域とヘッダーが揃っているべきだと思います。

**Comment by zr-tex8r** [comment]
ltjsbookはレイアウト設定に関してjsbookと同じ特質をもつので、geometryパッケージを使う場合に注意が必要なのですが、必要な対処ができていないために奇妙なことになっています。

  * (lt)jsbookでは実際にヘッダと本文で異なる横幅をとるデザインになっている。
      * 参考：[jsbook や bxjsbook の左右マージンを理解する](http://d.hatena.ne.jp/zrbabbler/20160821/1471761996)

  * このため、(lt)jsbookには、`\fullwidth`という独自の長さパラメタが存在し、`\fullwidth`がヘッダの横幅、`\textwidth`が本文の横幅を表す。
  * geometryでレイアウトを再設定する場合、独自のパラメタである`\fullwidth`は変更されない。ヘッダは`\fullwidth`の幅で組むというロジックも変更されない。
  * 従って、(lt)jsbookのレイアウトを破棄してgeometryで新たに設定しているにも関わらず、ヘッダの横幅だけ元のデザインのものが踏襲される。これは意図した動作ではないはず。
  * 「ヘッダの横幅をどうするか」の方針を決めて、`\fullwidth`をその幅に自分で設定する必要がある。

**Comment by zr-tex8r** [comment]
単純に、`\fullwidth`を「geometryが設定した`\textwidth`」に合わせる場合：

```latex
\setlength{\fullwidth}{\textwidth}
```

**Comment by y-yu** [comment]
@zr-tex8r 

なるほど、ltjsbookの特質をまるで理解せずに使っていました。とりあえず、提案いただいた方法で直すことにします！
