### ISSUE TITLE
コード前後の和欧文間の空きがおかしい

### ISSUE THREAD

**Issue by scivola** [y-yu/trpl-2nd-pdf#35]
和文中にコードが入ったとき，左側には和欧文間の空きが出来ますが，右側がベタ（空きが無いこと）になります。

たとえば，「2.1.4  Rustupなしでカスタムインストール」の

> なんらかの理由でrustupを使用しないことを好むのなら

の箇所で，「rustup」の左は空いていますが，右が空いていません。
TeX ではどういうコードになっているのですか？

**Comment by y-yu** [comment]
これですね。

![image](https://user-images.githubusercontent.com/612043/39709974-69289f78-5256-11e8-88c2-4c845866b3b8.png)

**Comment by nmtake** [comment]
元の Markdown がこうなっていて、

```
### Rustupなしでカスタムインストール

<!-- If you prefer not to use `rustup` for some reason, please see [the Rust -->
<!-- installation page](https://www.rust-lang.org/install.html) for other options. -->

なんらかの理由で`rustup`を使用しないことを好むのなら、他の選択肢を求めて、
[Rustのインストールページ](https://www.rust-lang.org/install.html)をご覧ください。
```

それを pandoc で LaTeX に変換したものがこちらです：

```
\subsection{Rustupなしでカスタムインストール}

なんらかの理由で\passthrough{\lstinline!rustup!}を使用しないことを好むのなら、他の選択肢を求めて、
\href{https://www.rust-lang.org/install.html}{Rustのインストールページ}をご覧ください。
```

luatex-ja とか listings 周り？ よく起こりそうな問題なのですでに誰かが解決してそうな気もします。

**Comment by y-yu** [comment]
@scivola 

基本的に和文と欧文の間のスペースはTeXエンジンが判断して入れるので、Markdownをいじってもらう必要はないと思います。`\lstinline`が中で特殊なことをやっていて、スペーシングがうまく動いてないようですね。

**Comment by y-yu** [comment]
`\passthrough`はPandocが出力する独自のコマンドで、これはいちおう何もしないように処理してありますが、ためしに`\passthrough`を手で消してみても状況は変化しませんね。ちょっとLaTeXのエキスパートと相談してみます。
