### ISSUE TITLE
PDF に表示されていない文字がある

### ISSUE THREAD

**Issue by nmtake** [y-yu/trpl-2nd-pdf#42]
今までに確認できたのは以下です：

    ch02-00-guessing-game-tutorial.md 👍  (U+1F44D)
    ch02-00-guessing-game-tutorial.md 👍  (U+1F44D)
    ch03-02-data-types.md 😻  (U+1F63B)
    ch03-02-data-types.md  ℤ (U+2124)

https://doc.rust-lang.org/book/second-edition/ch03-02-data-types.html#the-character-type :

![screen shot](https://user-images.githubusercontent.com/18096192/39967887-92648fb2-56fe-11e8-9da4-db109a92fff1.png)

https://y-yu.github.io/trpl-2nd-pdf/book.pdf (p. 41):

![screen shot](https://user-images.githubusercontent.com/18096192/39967889-98e94d6e-56fe-11e8-989a-84d375e0b44d.png)

参考までに、PDF のビルド時にに作成される book.log から以下の行も見つかりました（上の 3 つ以外は本文中で見たことがないので無視してもよさそうに思います）：

```
3248:Missing character: There is no 👍 (U+1F44D) in font SourceCodePro:mode=node;sc
3904:Missing character: There is no ℤ (U+2124) in font IPAExMincho:-kern;script=han
3906:Missing character: There is no 😻 (U+1F63B) in font SourceCodePro:mode=node;sc
10669:Missing character: There is no ا (U+0627) in font SourceCodePro:mode=node;scrip
... snip ...
38927:Missing character: There is no ת (U+05EA) in font [lmroman10-regular]:+tlig;!
```

**Comment by scivola** [comment]
[appendix-05-translation.md](https://github.com/hazama-yuinyan/book/blob/master/second-edition/src/appendix-05-translation.md) で，漢字の「简」，キリル文字の「ї」，ハングルの「한국어」，ヘブライ文字「עברית」が見えてないようです。
また，キリル文字「Українська」「Русский」が全角になっています。

**Comment by nmtake** [comment]
Appendix E は見落としてました。絵文字以外も欠落してますね。

`rg -i 'missing char' book.log` して得たリストを今度は省略せずに貼ります（コードポイント順）：

```
Missing character: There is no ї (U+0457) in font IPAExMincho:-kern;script=hani
Missing character: There is no ָ (U+05B8) in font SourceCodePro:mode=node;scrip
Missing character: There is no ֹ (U+05B9) in font SourceCodePro:mode=node;scrip
Missing character: There is no ׁ (U+05C1) in font SourceCodePro:mode=node;scrip
Missing character: There is no ב (U+05D1) in font [lmroman10-regular]:+tlig;!
Missing character: There is no ו (U+05D5) in font SourceCodePro:mode=node;scrip
Missing character: There is no י (U+05D9) in font [lmroman10-regular]:+tlig;!
Missing character: There is no ל (U+05DC) in font SourceCodePro:mode=node;scrip
Missing character: There is no ם (U+05DD) in font SourceCodePro:mode=node;scrip
Missing character: There is no ע (U+05E2) in font [lmroman10-regular]:+tlig;!
Missing character: There is no ר (U+05E8) in font [lmroman10-regular]:+tlig;!
Missing character: There is no ש (U+05E9) in font SourceCodePro:mode=node;scrip
Missing character: There is no ת (U+05EA) in font [lmroman10-regular]:+tlig;!
Missing character: There is no ا (U+0627) in font SourceCodePro:mode=node;scrip
Missing character: There is no س (U+0633) in font SourceCodePro:mode=node;scrip
Missing character: There is no ع (U+0639) in font SourceCodePro:mode=node;scrip
Missing character: There is no ك (U+0643) in font SourceCodePro:mode=node;scrip
Missing character: There is no ل (U+0644) in font SourceCodePro:mode=node;scrip
Missing character: There is no م (U+0645) in font SourceCodePro:mode=node;scrip
Missing character: There is no ي (U+064A) in font SourceCodePro:mode=node;scrip
Missing character: There is no त (U+0924) in font SourceCodePro:mode=node;scri
Missing character: There is no त (U+0924) in font [lmroman10-regular]:+tlig;!
Missing character: There is no न (U+0928) in font SourceCodePro:mode=node;scri
Missing character: There is no न (U+0928) in font [lmroman10-regular]:+tlig;!
Missing character: There is no म (U+092E) in font SourceCodePro:mode=node;scri
Missing character: There is no म (U+092E) in font [lmroman10-regular]:+tlig;!
Missing character: There is no स (U+0938) in font SourceCodePro:mode=node;scri
Missing character: There is no स (U+0938) in font [lmroman10-regular]:+tlig;!
Missing character: There is no े (U+0947) in font SourceCodePro:mode=node;scri
Missing character: There is no े (U+0947) in font [lmroman10-regular]:+tlig;!
Missing character: There is no ् (U+094D) in font SourceCodePro:mode=node;scri
Missing character: There is no ् (U+094D) in font [lmroman10-regular]:+tlig;!
Missing character: There is no ℤ (U+2124) in font IPAExMincho:-kern;script=han
Missing character: There is no 简 (U+7B80) in font IPAExMincho:-kern;script=han
Missing character: There is no 국 (U+AD6D) in font IPAExMincho:-kern;script=han
Missing character: There is no 녕 (U+B155) in font IPAExMincho:-kern;script=han
Missing character: There is no 세 (U+C138) in font IPAExMincho:-kern;script=han
Missing character: There is no 안 (U+C548) in font IPAExMincho:-kern;script=han
Missing character: There is no 어 (U+C5B4) in font IPAExMincho:-kern;script=han
Missing character: There is no 요 (U+C694) in font IPAExMincho:-kern;script=han
Missing character: There is no 하 (U+D558) in font IPAExMincho:-kern;script=han
Missing character: There is no 한 (U+D55C) in font IPAExMincho:-kern;script=han
Missing character: There is no 👍 (U+1F44D) in font SourceCodePro:mode=node;sc
Missing character: There is no 😻 (U+1F63B) in font SourceCodePro:mode=node;sc
```

**Comment by y-yu** [comment]
今ソースコードに利用しているSourceCodeProにはどうやら絵文字がはいってないので、入っている別のフォントへ変更するのがよさそうですね。

**Comment by y-yu** [comment]
うーん、これはちょっとLaTeXのエキスパートじゃないと対処できないかも……。

**Comment by scivola** [comment]
単一のフォントで解決するのは無理なのではないでしょうか。

**Comment by nmtake** [comment]
やや進展があったので報告です。luatexja-fontspec の AltFont を使って代替フォントを指定してみました。

https://github.com/nmtake/trpl-2nd-pdf/commit/d1d3452e4fce3d17582b1042adae5b66f63bad65

上のコミットはデモ用なので以下の問題があります：

1. ファイルに必要なフォントのダウンロード処理を省いている
2. book.tex の環境変数に応じて使用フォントを切り替える Lua コードを一時的に削除している
3. キリル文字とヘブライ文字も JAchar に指定したせいか文字間が広くなっている
4. ヘブライ文字 עברית が逆順になっている（RTL のせい？ polyglossia や hebrew を使う必要がある？）
5. フォントのプリセットを使わないので本文の見た目に影響が出てるかもしれない

![screen shot 2018-06-19 at 23 40 16](https://user-images.githubusercontent.com/18096192/41604468-49ee90be-741a-11e8-9aa1-6a714cc2866b.png)

このへんで正直いっぱいいっぱいです。エキスパートの解法が見てみたい・・・

**Comment by nmtake** [comment]
Section 8.2 でヘブライ、サンスクリット、ハングル、キリル文字が抜け落ちてる箇所がありました。

[Mac + Firefox での表示](https://doc.rust-lang.org/book/second-edition/ch08-02-strings.html#creating-a-new-string):

![screen shot 2018-06-21 at 00 23 38](https://user-images.githubusercontent.com/18096192/41668187-bdbe7cc8-74e9-11e8-9ec8-bde4cd0ecaf5.png)

[現行の PDF の表示](https://y-yu.github.io/trpl-2nd-pdf/book.pdf):

![screen shot 2018-06-21 at 00 24 03](https://user-images.githubusercontent.com/18096192/41668266-eb45e082-74e9-11e8-97a1-119e6a9ce404.png)
![screen shot 2018-06-21 at 00 24 09](https://user-images.githubusercontent.com/18096192/41668273-f4f8e304-74e9-11e8-9e64-9fcdd3d17b0f.png)

これで[前出のログ](https://github.com/y-yu/trpl-2nd-pdf/issues/42#issuecomment-388666457)で警告が出ていた特別な文字が使われてる箇所は一通り出揃ったと思います：

* section 3.2: 文字列リテラルの絵文字と数学記号
* section 8.2: 文字列リテラルのヘブライ、サンスクリット、ハングル、キリル
* appendix E: 簡体中文、キリル、ハングル、ヘブライ

**Comment by y-yu** [comment]
section8.2についてはソースコードのフォントを[DejaVu
](https://ja.wikipedia.org/wiki/DejaVu%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88)に変更してみる、というのをやってみます。

**Comment by nmtake** [comment]
時間の都合で 3 章だけビルドすると同様のエラーが出ました。
そのエラーのあとに Enter を押すと、

```
! Missing number, treated as zero.
<to be read again>
\global
l.14 let
       guess: u32 = "42".parse().expect("Not a number!");    // 󿿿数󿿿字.
..
?
...exlive/2017/texmf-dist/tex/luatex/luatexja/ltj-jfont.lua:684: attempt to ind
ex a nil value
stack traceback:
        ...exlive/2017/texmf-dist/tex/luatex/luatexja/ltj-jfont.lua:684: in function '
pickup_alt_font_b'
        [\directlua]:1: in main chunk.
\ltj@pickup@altfont@copy ...uaescapestring {#2}')}
```

と出てきて、その ltj-jfont.lua: 684 には

```
   function pickup_alt_font_b(afnt_num, afnt_base)
      local t = alt_font_table[alt_font_base_num]
      local ac = font_getfont(afnt_num).characters  # 684
      if not t then t = {}; alt_font_table[alt_font_base_num] = t end
```

とあるので代替フォントの指定に問題が有るのかも？
ltj-jfont.lua と patches/lltjfont.sty 頑張って読んだら何かわかったりするんでしょうか・・・

**Comment by nmtake** [comment]
"Missing characters" がログからなんとか消せました。

https://github.com/nmtake/trpl-2nd-pdf/commit/091cb198e50e154702173ff06adfd89e83f487ce

コミットログに書いた通りなにかと問題も多いんですが目を通してもらえるとうれしいです。  
もし間違った方向に向かってないなら破損してる目次をなんとか直して PR したいと思います。
