### ISSUE TITLE
* * がイタリックになっていないところがある

### ISSUE THREAD

**Issue by scivola** [y-yu/trpl-2nd-pdf#7]
`* *` で囲まれているのにイタリックにならず `* *` がそのまま出ている個所があります。

「3.2.2  Rust プログラムを書いて走らせる」の最初の段落ですが，ソースは

```
次にソースファイルを作り、*main.rs*と呼んでください。Rustのファイルは常に*.rs*という拡張子で終わります。
ファイル名に2単語以上使っているなら、アンダースコアで区切ってください。例えば、*helloworld.rs*ではなく、
*hello_world.rs*を使用してください。
```

ですが，`*helloworld.rs*` のほうはイタリックになっているのに，`*hello_world.rs*` はそのまま出ています。

**Comment by y-yu** [comment]
@scivola 

これはPandocの設定ミスな予感がしますね。
今はこの:point_right:`markdown_github+footnotes+header_attributes-hard_line_breaks-intraword_underscores`:point_left:オプションで変換していますが、ちょっとPandocのドキュメントを見つつ見直します！

**Comment by scivola** [comment]
Pandoc を全く知らないもので，私には手も足も出ませんでした。よろしくお願いします。
